### ISSUE TITLE
Json.RawValue quoted with double quotes when using jackson >= 2.4

### ISSUE THREAD

**Issue by pulse00** [l0rdn1kk0n/wicket-jquery-selectors#11]
We've updated our projects dependencies to `jackson-core / 2.4.1` which breaks the serialization of `Json.RawValue`. They are now quoted with double quotes.

#### Jackson < 2.4

` { "queryString": bloodhound.ttAdapter() }` 

#### With jackson-core / >= 2.4

` { "queryString: "bloodhound.ttAdapter()" }`

I've tried to provide a custom Serializer for `Json.RawValue` by overriding [serialize](https://github.com/l0rdn1kk0n/wicket-jquery-selectors/blob/ca5e1057cf3bdf3f64177daf36ea4039d66cad4c/src/main/java/de/agilecoders/wicket/jquery/util/serializer/RawSerializer.java#L18) with `jsonGenerator.writeRawValue(value.value());`, but then i get  `Called operation not supported for TokenBuffer`.

It looks like there have been some changes in [jackson-core 2.3.1](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.3.1) regarding the `RawSerializer` (related to https://github.com/FasterXML/jackson-module-afterburner/issues/38).

Is the project dependency set to `jackson-core / 2.3.0` because of this issue, or are we the first ones running into it?

**Comment by martin-g** [comment]
You are the first.

**Comment by pulse00** [comment]
Yes, it's definitely a regression when upgrading to jackson >= `2.4.0`, here's a screenshot of the failed test with 2.4.0 `AbstractConfigTest::rawValue`: 

![screen shot 2015-01-05 at 15 47 45](https://cloud.githubusercontent.com/assets/185278/5614538/74b38d5a-94f2-11e4-8b36-73997e53453e.png)

**Comment by gsmet** [comment]
I posted on the jackson thread to have some more guidance about how to fix this one.

**Comment by martin-g** [comment]
I've pushed some fixes which use Jackson 2.6.0-SNAPSHOT. Once it is released I'll merge the branch.
