### ISSUE TITLE
String2.escapeMarkupId() has to escape with two backslashes instead of one

### ISSUE THREAD

**Issue by johnjcool** [l0rdn1kk0n/wicket-jquery-selectors#23]
Could you please merge this pull request #22. Whether you use a special char in id selector then the js function is not triggerd. you can try this with TooltipBehavior of wicket bootstrap. It happens no javascript error but the tooltip is not triggered.

"If you wish to use any of the meta-characters ( such as !"#$%&'()*+,./:;<=>?@[\]^`{|}~ ) as a literal part of a name, you must escape the character with two backslashes: \\." - http://alexandregiannini.blogspot.de/2011/05/escaping-strings-for-jquery-selectors.html

**Comment by martin-g** [comment]
No need of a separate issue.
The PR (#22) is enough.
Thanks!
