### ISSUE TITLE
The fix for #21 led to unexpected failure in our codebase

### ISSUE THREAD

**Issue by bgooren** [l0rdn1kk0n/wicket-jquery-selectors#25]
Hi!

When we upgraded to wicket 7.7.0 and wicket-bootstrap 0.10.13, our unit tests started failing.
Debugging reveals that it's caused by an upgrade of the wicket-jquery-selectors from 0.2.3 to 0.2.5, and more specifically the fixes for issue #21 .

We use quite a lot of ```JavaScriptInlineFunction``` instances, which now break when used in another jquery call, e.g.:

```
JavaScriptInlineFunction focusFunction = new JavaScriptInlineFunction( //
                    JQuery.$( componentToFocus ).chain( "focus" ).chain( "select" ).build() //
            );
            String focusOnShowHandler = JQuery.$( this ).on( "shown.bs.modal", focusFunction ).build();
```

The reason this now fails is that the ```JavascriptInlineFunction``` gets a new "evt" parameter when connecting it to "shown.bs.modal"; See ```OnJqueryFunction``` line 110:

```
handler.addParameter("evt");
```

As the constructor of ```JavascriptInlineFunction``` has been changed to

```
public JavaScriptInlineFunction(final String functionBody) {
        this(functionBody, Collections.<CharSequence>emptyList());
    }
```

the list of handlers is now an empty list which does not support the ```add(item)``` operation, throwing an ```UnsupportedOperationException```.

The fix was easy enough, we changed our code to

```
JavaScriptInlineFunction focusFunction = new JavaScriptInlineFunction( //
                    JQuery.$( componentToFocus ).chain( "focus" ).chain( "select" ).build(), //
                    new ArrayList<>() //
            );
            String focusOnShowHandler = JQuery.$( this ).on( "shown.bs.modal", focusFunction ).build();
```
(notice the added ```new ArrayList<>()``` parameter to the ```JavascriptInlineFunction``` constructor).

However, this was certainly unexpected and took some debugging to find. I think it would make more sense to change the constructor so it sets an empty arraylist as parameter instead of an empty list, since other code expects said list to always be writable.

**Comment by martin-g** [comment]
Thank you!
0.2.6 is on its way to Maven Central!
