### ISSUE TITLE
Guava dependency is very old and breaks other code

### ISSUE THREAD

**Issue by jcklie** [l0rdn1kk0n/wicket-jquery-selectors#26]
Hello,

this project uses a very old Guava version of 18 whereas the newest is 23 or so. This old dependency breaks other code in an application which uses *wicket-jquery-selectors* e.g. https://github.com/springfox/springfox/issues/441 or https://github.com/ronmamo/reflections/issues/194 . It would be really nice if the version could be bumped and the fix backported to the minor versions.

**Comment by martin-g** [comment]
Updated it to 21.0 in the branches for Wicket 6.x and Wicket 7.x.
Replaced it with Java 8 utils in 2.x (Wicket 8.x). You are recommended to upgrade to Wicket 8.x!

**Comment by martin-g** [comment]
I chose 21.0 because there are functionalities removed in 22.0 and they break my main application.
