### ISSUE TITLE
$. without braket

### ISSUE THREAD

**Issue by dutrieux** [l0rdn1kk0n/wicket-jquery-selectors#27]
I try to produce this jquery :

```javascript
$.extend(true, Chart.defaults.global, {defaultFontColor : 'red'})
```

and in java something like this :

```java
$().chain(new Function('extend', JQuery.plain("Chart.default.global"), global.build())
```

but at this time it's not possible to produce $ without brakets with the library

**Comment by martin-g** [comment]
Please see https://github.com/l0rdn1kk0n/wicket-jquery-selectors/commit/7cb10ffc8a9660c6339571b0d908c8417882b75f and test it with 2.0.3-SNAPSHOT from Sonatype OSS Snapshots repo (or build `wicket-8.x` locally).
If it works fine I will make a release.

**Comment by dutrieux** [comment]
Perfect thx !

**Comment by martin-g** [comment]
Do you confirm that I can make a release ?

**Comment by dutrieux** [comment]
Yes of course , I test it, that's work nicely !

**Comment by martin-g** [comment]
2.0.3 for Wicket 8.x has been released!
