### ISSUE TITLE
[JQuery] combine multi JQuery to obtain one JQuery

### ISSUE THREAD

**Issue by dutrieux** [l0rdn1kk0n/wicket-jquery-selectors#29]
Hello,

Is there a possibility to combine multiples JQuery to obtain one JQuery :

Like this :

```
JQuery componant1JQuery = $(componant1).chain('show');
JQuery componant2JQuery = $(componant2).chain('hide');

public JQuery combine(JQuery... jQueries) {
....
}

JQuery combineJQuerie = combine(componant1JQuery , componant2JQuery);
```

I try to find a solution but I don't

Thx for your help

Duto

**Comment by martin-g** [comment]
No, there is no such API at the moment.
If you manage to implement it then please send a Pull Request.
